(()=>{
const parts={
 cpu:{label:'Процессор',options:[{id:'a6',name:'CPU A6 · 6 ядер / 12 потоков',price:15900,socket:'AM5',watts:90,cores:6},{id:'a8',name:'CPU A8 · 8 ядер / 16 потоков',price:25900,socket:'AM5',watts:120,cores:8},{id:'i6',name:'CPU I6 · 6 ядер / 12 потоков',price:13900,socket:'LGA1700',watts:110,cores:6}]},
 board:{label:'Материнская плата',options:[{id:'b650',name:'Плата B650 · AM5 / DDR5 / ATX',price:14900,socket:'AM5',ram:'DDR5',size:'ATX'},{id:'b660',name:'Плата B660 · LGA1700 / DDR4 / mATX',price:9900,socket:'LGA1700',ram:'DDR4',size:'mATX'},{id:'b760',name:'Плата B760 · LGA1700 / DDR5 / ATX',price:13900,socket:'LGA1700',ram:'DDR5',size:'ATX'}]},
 ram:{label:'Оперативная память',options:[{id:'d5-32',name:'32 ГБ · 2 × 16 ГБ DDR5',price:10900,ram:'DDR5',gb:32},{id:'d5-64',name:'64 ГБ · 2 × 32 ГБ DDR5',price:19900,ram:'DDR5',gb:64},{id:'d4-16',name:'16 ГБ · 2 × 8 ГБ DDR4',price:4900,ram:'DDR4',gb:16}]},
 gpu:{label:'Видеокарта',options:[{id:'g8',name:'Graphics 8 · 8 ГБ / 2 вентилятора',price:32900,watts:160,length:250,gb:8},{id:'g12',name:'Graphics 12 · 12 ГБ / 3 вентилятора',price:54900,watts:230,length:320,gb:12},{id:'g16',name:'Graphics 16 · 16 ГБ / 3 вентилятора',price:79900,watts:320,length:340,gb:16}]},
 ssd:{label:'Накопитель',options:[{id:'s512',name:'NVMe SSD · 512 ГБ',price:3900,gb:512},{id:'s1',name:'NVMe SSD · 1 ТБ',price:6900,gb:1024},{id:'s2',name:'NVMe SSD · 2 ТБ',price:11900,gb:2048}]},
 cooler:{label:'Охлаждение',options:[{id:'c150',name:'Башенный кулер · до 150 Вт',price:2900,capacity:150,height:150,sockets:['AM5','LGA1700']},{id:'c220',name:'Двухбашенный кулер · до 220 Вт',price:5900,capacity:220,height:165,sockets:['AM5','LGA1700']}]},
 psu:{label:'Блок питания',options:[{id:'p500',name:'500 Вт · 80 Plus Bronze',price:4900,capacity:500},{id:'p650',name:'650 Вт · 80 Plus Gold',price:7900,capacity:650},{id:'p850',name:'850 Вт · 80 Plus Gold',price:11900,capacity:850}]},
 case:{label:'Корпус',options:[{id:'tower',name:'Air Tower · ATX · чёрный',price:6900,maxGpu:360,maxCooler:170,sizes:['ATX','mATX'],color:'#222b33'},{id:'white',name:'Air Tower · ATX · белый',price:7900,maxGpu:360,maxCooler:170,sizes:['ATX','mATX'],color:'#d5dde1'},{id:'mini',name:'Compact · mATX · чёрный',price:4900,maxGpu:280,maxCooler:155,sizes:['mATX'],color:'#222b33'}]}
};
let selection={cpu:'a6',board:'b650',ram:'d5-32',gpu:'g8',ssd:'s1',cooler:'c150',psu:'p650',case:'tower'},angle=-28,tilt=-12,exploded=false;
try{let saved=JSON.parse(localStorage.getItem('klamas-build-v1'));if(saved)for(const k in parts)if(parts[k].options.some(p=>p.id===saved[k]))selection[k]=saved[k]}catch{}
const el=id=>document.getElementById(id),rub=n=>new Intl.NumberFormat('ru-RU').format(n)+' ₽';
function chosen(){return Object.fromEntries(Object.keys(parts).map(k=>[k,parts[k].options.find(p=>p.id===selection[k])]))}
function evaluate(s=chosen()){let errors=[];if(s.cpu.socket!==s.board.socket)errors.push('Сокет процессора не подходит к материнской плате.');if(s.ram.ram!==s.board.ram)errors.push('Тип памяти не подходит к материнской плате.');if(!s.case.sizes.includes(s.board.size))errors.push('Материнская плата не помещается в корпус.');if(s.gpu.length>s.case.maxGpu)errors.push('Видеокарта длиннее допустимого размера корпуса.');if(s.cooler.height>s.case.maxCooler)errors.push('Кулер выше допустимого размера корпуса.');if(s.cooler.capacity<s.cpu.watts)errors.push('Недостаточная мощность охлаждения.');const load=s.cpu.watts+s.gpu.watts+70,recommended=Math.ceil(load*1.25/50)*50;if(s.psu.capacity<recommended)errors.push('Для запаса мощности выберите БП от '+recommended+' Вт.');return{errors,load,recommended,total:Object.values(s).reduce((n,p)=>n+p.price,0)}}
const mount=document.createElement('section');mount.id='pc-builder';mount.className='pc-builder';mount.innerHTML=`<div class="builder-heading"><div><span class="builder-eyebrow">КОНФИГУРАТОР ПК</span><h2>Соберите свой компьютер<span>.</span></h2></div><span class="builder-demo">Демо-комплектующие и цены</span></div><div class="build-presets"><button data-preset="base">Сбалансированный</button><button data-preset="power">Для сложных задач</button><button data-preset="compact">Компактный</button></div><div class="builder-layout"><div class="builder-visual"><div class="scene-toolbar"><span>3D / ваша сборка</span><button id="explode-pc" aria-pressed="false">Разнести детали</button></div><div class="pc-scene" id="pc-scene" tabindex="0" role="img" aria-label="Вращаемая 3D-модель компьютера. Перетаскивайте или используйте стрелки."><div class="pc-shadow"></div><div class="pc-world" id="pc-world"></div></div><div class="scene-actions"><button id="rotate-left" aria-label="Повернуть компьютер влево">↶</button><span>Потяните, чтобы повернуть</span><button id="rotate-right" aria-label="Повернуть компьютер вправо">↷</button><button id="reset-camera">Сбросить вид</button></div><div class="build-specs" id="build-specs"></div><p class="model-note">Схематичная 3D-модель. Реальный вид зависит от выбранных моделей.</p></div><div class="builder-components" id="builder-components"></div></div><div class="builder-bottom"><div class="build-compat" id="build-compat" role="status"></div><div class="build-total"><span>Стоимость комплектующих</span><strong id="build-total"></strong><button class="primary" id="save-build">Сохранить сборку</button><button class="build-download" id="download-build">Скачать спецификацию ↓</button><span id="build-saved" role="status"></span></div></div><p class="builder-footnote">Проверяем сокет, память, размеры, охлаждение и запас мощности БП. BIOS, разъёмы и точную совместимость реальных моделей нужно подтвердить перед заказом.</p>`;
document.querySelector('.business-intro').before(mount);
function box(name,x,y,z,w,h,d,color,content='',extra=''){return `<div class="pc-part ${extra}" data-part="${name}" style="--x:${x}px;--y:${y}px;--z:${z}px;--w:${w}px;--h:${h}px;--d:${d}px;--part-color:${color}"><div class="face front">${content}</div><div class="face back"></div><div class="face left"></div><div class="face right"></div><div class="face top"></div><div class="face bottom"></div></div>`}
function fan(){return '<i class="pc-fan"><i></i></i>'}
function model(){let s=chosen(),c=s.case.color;el('pc-world').innerHTML=box('case',0,0,0,240,335,145,c,'','chassis')+box('rear',-1,0,-71,235,330,5,c)+box('base',0,165,0,240,8,145,c)+box('roof',0,-165,0,240,8,145,c)+box('front',118,0,0,8,330,145,c,'')+box('board',-25,-22,-61,155,220,6,'#283b3d','<b class="board-traces"></b>')+box('cpu',-45,-60,-42,48,48,25,'#77848e','<span class="part-label">CPU</span>')+box('cooler',-45,-60,-12,65,70,44,'#465663',fan())+box('ram',34,-55,-42,12,100,24,'#ec6e49','')+box('ram',53,-55,-42,12,100,24,'#ec6e49','')+box('gpu',-8,62,12,s.gpu.length/1.6,40,95,'#3d4853',`<div class="gpu-fans">${fan()}${fan()}${s.gpu.gb>8?fan():''}</div><span class="gpu-label">${s.gpu.gb} GB GRAPHICS</span>`)+box('ssd',-49,8,-48,65,14,7,'#bfb19a','<span class="ssd-label">NVMe</span>')+box('psu',-40,129,-1,145,60,125,'#303840',`<span class="part-label">${s.psu.capacity}W</span>`)+[ -98,0,98].map(y=>box('fan',113,y,0,4,77,95,'#252f37',fan(),'intake')).join('');el('pc-world').style.setProperty('--case-color',c);camera();}
function camera(){el('pc-world').style.transform=`rotateX(${tilt}deg) rotateY(${angle}deg)`;el('pc-world').classList.toggle('exploded',exploded)}
function render(){let s=chosen(),r=evaluate(s);el('builder-components').innerHTML=Object.entries(parts).map(([k,p],i)=>`<div class="component-row"><span class="component-index">${String(i+1).padStart(2,'0')}</span><label for="component-${k}">${p.label}<select id="component-${k}" data-component="${k}">${p.options.map(o=>`<option value="${o.id}" ${selection[k]===o.id?'selected':''}>${o.name}</option>`).join('')}</select></label><b>${rub(s[k].price)}</b></div>`).join('');el('build-total').textContent=rub(r.total);el('build-specs').innerHTML=`<div><small>Процессор</small><b>${s.cpu.cores} ядер</b></div><div><small>ОЗУ</small><b>${s.ram.gb} ГБ</b></div><div><small>SSD</small><b>${s.ssd.gb===512?'512 ГБ':s.ssd.gb/1024+' ТБ'}</b></div><div><small>Расчётная нагрузка</small><b>≈ ${r.load} Вт</b></div>`;el('build-compat').classList.toggle('has-errors',!!r.errors.length);el('build-compat').innerHTML=r.errors.length?`<strong>Нужно исправить: ${r.errors.length}</strong><ul>${r.errors.map(e=>`<li>${e}</li>`).join('')}</ul>`:`<strong>✓ По базовым параметрам всё подходит</strong><p>Блок питания: ${s.psu.capacity} Вт. Рекомендуемый минимум с запасом: ${r.recommended} Вт.</p>`;el('save-build').disabled=!!r.errors.length;el('build-saved').textContent='';model();}
mount.addEventListener('change',e=>{if(e.target.dataset.component){selection[e.target.dataset.component]=e.target.value;render()}});
mount.addEventListener('click',e=>{let b=e.target.closest('button');if(!b)return;if(b.dataset.preset){const p=b.dataset.preset;selection=p==='compact'?{cpu:'i6',board:'b660',ram:'d4-16',gpu:'g8',ssd:'s512',cooler:'c150',psu:'p650',case:'mini'}:p==='power'?{cpu:'a8',board:'b650',ram:'d5-64',gpu:'g16',ssd:'s2',cooler:'c220',psu:'p850',case:'white'}:{cpu:'a6',board:'b650',ram:'d5-32',gpu:'g8',ssd:'s1',cooler:'c150',psu:'p650',case:'tower'};render()}if(b.id==='explode-pc'){exploded=!exploded;b.setAttribute('aria-pressed',String(exploded));b.textContent=exploded?'Собрать корпус':'Разнести детали';camera()}if(b.id==='rotate-left'){angle-=30;camera()}if(b.id==='rotate-right'){angle+=30;camera()}if(b.id==='reset-camera'){angle=-28;tilt=-12;camera()}if(b.id==='save-build'){try{localStorage.setItem('klamas-build-v1',JSON.stringify(selection));el('build-saved').textContent='Сборка сохранена на этом устройстве'}catch{el('build-saved').textContent='Браузер запретил сохранение. Скачайте спецификацию.'}}if(b.id==='download-build'){const s=chosen(),r=evaluate(s),text='КЛАМАС — ДЕМОНСТРАЦИОННАЯ СБОРКА\nЦены и комплектующие условные. Не оферта.\n\n'+Object.entries(parts).map(([k,p])=>p.label+': '+s[k].name+' — '+rub(s[k].price)).join('\n')+'\n\nИтого: '+rub(r.total)+'\nРасчётная нагрузка: '+r.load+' Вт\n'+(r.errors.join('\n')||'Базовые проверки пройдены');const u=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'})),a=document.createElement('a');a.href=u;a.download='klamas-pc-build.txt';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}});
let drag=null;el('pc-scene').addEventListener('pointerdown',e=>{drag={x:e.clientX,y:e.clientY,a:angle,t:tilt};e.currentTarget.setPointerCapture(e.pointerId)});el('pc-scene').addEventListener('pointermove',e=>{if(!drag)return;angle=drag.a+(e.clientX-drag.x)*.65;tilt=Math.max(-50,Math.min(50,drag.t-(e.clientY-drag.y)*.35));camera()});['pointerup','pointercancel'].forEach(t=>el('pc-scene').addEventListener(t,()=>drag=null));el('pc-scene').addEventListener('keydown',e=>{if(!e.key.startsWith('Arrow'))return;e.preventDefault();if(e.key==='ArrowLeft')angle-=15;if(e.key==='ArrowRight')angle+=15;if(e.key==='ArrowUp')tilt=Math.max(-50,tilt-10);if(e.key==='ArrowDown')tilt=Math.min(50,tilt+10);camera()});render();
})();
