// Bound Google Apps Script. Install in the private B2B spreadsheet.
function db_(){return SpreadsheetApp.getActiveSpreadsheet()||SpreadsheetApp.openById(PropertiesService.getScriptProperties().getProperty('SHEET_ID'));}
function rows_(name){const sh=db_().getSheetByName(name);if(!sh)throw Error('Нет листа '+name);const values=sh.getDataRange().getValues(),keys=values.shift();return values.map((r,i)=>Object.assign({_row:i+2},Object.fromEntries(keys.map((k,j)=>[k,r[j] instanceof Date?Utilities.formatDate(r[j],'Asia/Yekaterinburg','dd.MM.yyyy HH:mm'):r[j]])))).filter(r=>r[keys[0]]);}
function uuid_(){return Utilities.getUuid().replace(/-/g,'');}
function digest_(s){return Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,s,Utilities.Charset.UTF_8).map(b=>('0'+((b+256)%256).toString(16)).slice(-2)).join('');}
function pepper_(){const p=PropertiesService.getScriptProperties();let v=p.getProperty('AUTH_PEPPER');if(!v)throw Error('Сначала выполните установку.');return v;}
function append_(sheet,values){const sh=db_().getSheetByName(sheet),first=sh.getRange(1,1,sh.getMaxRows(),1).getValues();let row=first.findIndex((v,i)=>i>0&&!v[0])+1;if(row<2)row=sh.getLastRow()+1;if(row>sh.getMaxRows())sh.insertRowsAfter(sh.getMaxRows(),100);sh.getRange(row,1,1,values.length).setValues([values]);return row;}
function safeText_(v,max){const s=String(v||'').trim().slice(0,max);return /^[=+@-]/.test(s)?"'"+s:s;}
function event_(u,event,object){append_('Журнал',['EV-'+uuid_().slice(0,12),new Date(),u['ID пользователя'],u['ID компании'],event,object||'']);}
function authorize_(token){if(typeof token!=='string'||!/^[a-f0-9]{64}$/.test(token))throw Error('Войдите в кабинет.');const c=CacheService.getScriptCache(),session=c.get('session:'+digest_(token));if(!session)throw Error('Сессия завершена. Войдите снова.');const a=JSON.parse(session),u=rows_('Пользователи').find(u=>u['ID пользователя']===a.uid&&u['Статус']==='Активен'&&u['Хеш ключа']===a.keyHash),company=u&&rows_('Компании').find(x=>x['ID компании']===u['ID компании']&&x['Статус']==='Активна');if(!company)throw Error('Доступ отключён. Обратитесь к менеджеру.');return{user:u,company};}
function login(email,key){if(typeof email!=='string'||typeof key!=='string'||email.length>254||key.length>200)throw Error('Неверные данные входа.');email=email.trim().toLowerCase();const lock=LockService.getScriptLock();lock.waitLock(10000);try{const cache=CacheService.getScriptCache(),bucket='attempt:'+digest_(email),n=Number(cache.get(bucket)||0);if(n>=8)throw Error('Слишком много попыток. Повторите через 15 минут.');cache.put(bucket,String(n+1),900);const u=rows_('Пользователи').find(u=>String(u.Email).trim().toLowerCase()===email),hash=digest_(pepper_()+':'+key),company=u&&rows_('Компании').find(c=>c['ID компании']===u['ID компании']);if(!u||u['Статус']!=='Активен'||!company||company['Статус']!=='Активна'||!u['Хеш ключа']||hash!==u['Хеш ключа'])throw Error('Неверные данные входа или доступ отключён.');cache.remove(bucket);const token=uuid_()+uuid_();cache.put('session:'+digest_(token),JSON.stringify({uid:u['ID пользователя'],keyHash:hash}),3600);db_().getSheetByName('Пользователи').getRange(u._row,8).setValue(new Date());event_(u,'Вход','');return{token};}finally{lock.releaseLock();}}
function logout(token){const auth=authorize_(token);CacheService.getScriptCache().remove('session:'+digest_(token));event_(auth.user,'Выход','');return true;}
function portalData(token){const {user,company}=authorize_(token),cid=company['ID компании'];const orders=rows_('Заказы').filter(o=>o['ID компании']===cid),ids=new Set(orders.map(o=>o['ID заказа'])),items=rows_('Позиции').filter(i=>ids.has(i['ID заказа'])),itemIds=new Set(items.map(i=>i['ID позиции'])),shipments=rows_('Отгрузки').filter(s=>ids.has(s['ID заказа'])),shipIds=new Set(shipments.map(s=>s['ID отгрузки'])),payments=rows_('Платежи').filter(p=>ids.has(p['ID заказа']));orders.forEach(o=>{o['Сумма, ₽']=items.filter(i=>i['ID заказа']===o['ID заказа']).reduce((s,i)=>s+Number(i.Количество||0)*Number(i['Цена, ₽']||0),0);o['Оплачено, ₽']=payments.filter(p=>p['ID заказа']===o['ID заказа']).reduce((s,p)=>s+(p.Статус==='Зачислен'?1:p.Статус==='Возврат'?-1:0)*Number(p['Сумма, ₽']||0),0);o['Остаток, ₽']=o['Сумма, ₽']-o['Оплачено, ₽'];});return{company:publicRow_('Компании',company),user:{name:user.Имя,role:user.Роль},orders:orders.map(r=>publicRow_('Заказы',r)),items:items.map(r=>publicRow_('Позиции',r)),shipments:shipments.map(r=>publicRow_('Отгрузки',r)),shipmentItems:rows_('Состав отгрузок').filter(x=>shipIds.has(x['ID отгрузки'])&&itemIds.has(x['ID позиции'])).map(r=>publicRow_('Состав отгрузок',r)),payments:payments.map(r=>publicRow_('Платежи',r)),documents:rows_('Документы').filter(d=>d['ID компании']===cid&&d.Статус==='Доступен'&&(!d['ID заказа']||ids.has(d['ID заказа']))).map(r=>publicRow_('Документы',r)),requests:rows_('Обращения').filter(r=>r['ID компании']===cid).map(r=>publicRow_('Обращения',r)),updated:Utilities.formatDate(new Date(),'Asia/Yekaterinburg','dd.MM.yyyy HH:mm')};}
function createRequest(token,subject,text){const {user}=authorize_(token);subject=String(subject||'').trim();text=String(text||'').trim();if(subject.length<3||subject.length>150||text.length<5||text.length>4000)throw Error('Тема: 3–150 символов. Сообщение: 5–4000 символов.');const lock=LockService.getScriptLock();lock.waitLock(10000);try{const cache=CacheService.getScriptCache(),key='request:'+user['ID пользователя'];if(cache.get(key))throw Error('Подождите минуту перед следующим обращением.');const id='REQ-'+uuid_().slice(0,12);append_('Обращения',[id,user['ID компании'],user['ID пользователя'],new Date(),safeText_(subject,150),safeText_(text,4000),'Новое','',new Date()]);cache.put(key,'1',60);event_(user,'Создано обращение',id);return{id};}finally{lock.releaseLock();}}
function doGet(){return HtmlService.createHtmlOutputFromFile('Portal').setTitle('Кламас — кабинет компании').addMetaTag('viewport','width=device-width, initial-scale=1');}
// Private menu handlers cannot be invoked by google.script.run.
function onOpen(){SpreadsheetApp.getUi().createMenu('Кламас B2B').addItem('Установить','setup_').addItem('Новая строка','newRow_').addItem('Выдать / заменить ключ','issueKey_').addToUi();}
function setup_(){const p=PropertiesService.getScriptProperties();p.setProperty('SHEET_ID',SpreadsheetApp.getActiveSpreadsheet().getId());if(!p.getProperty('AUTH_PEPPER'))p.setProperty('AUTH_PEPPER',uuid_()+uuid_());SpreadsheetApp.getUi().alert('Готово. Создайте пользователя и выдайте ему ключ через меню.');}
function issueKey_(){const sh=SpreadsheetApp.getActiveSheet(),r=sh.getActiveRange().getRow();if(sh.getName()!=='Пользователи'||r<2)throw Error('Выберите строку на листе Пользователи.');const vals=sh.getRange(r,1,1,8).getValues()[0];if(!vals[0]||!vals[1]||!vals[2])throw Error('Заполните ID пользователя, ID компании и Email.');const email=String(vals[2]).trim().toLowerCase();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))throw Error('Проверьте Email.');if(rows_('Пользователи').some(u=>u._row!==r&&String(u.Email).trim().toLowerCase()===email))throw Error('Этот Email уже используется.');if(!rows_('Компании').some(c=>c['ID компании']===vals[1]&&c.Статус==='Активна'))throw Error('Компания должна существовать и иметь статус Активна.');const key=uuid_()+uuid_();sh.getRange(r,3).setValue(email);sh.getRange(r,6).setValue('Активен');sh.getRange(r,7).setValue(digest_(pepper_()+':'+key));SpreadsheetApp.getUi().alert('Логин: '+email+'\nКлюч: '+key+'\n\nСкопируйте и передайте клиенту лично. Повторно ключ не показывается. Предыдущий ключ и его сессии отключены.');}
function formulas_(sh,r){if(sh.getName()==='Позиции')sh.getRange(r,8).setFormula('=IF(A'+r+'="","",IF(OR(E'+r+'="",G'+r+'=""),"",E'+r+'*G'+r+'))');if(sh.getName()==='Заказы'){sh.getRange(r,8).setFormula('=IF(A'+r+'="","",SUMIF(Позиции!B2:B,A'+r+',Позиции!H2:H))');sh.getRange(r,9).setFormula('=IF(A'+r+'="","",SUMIFS(Платежи!D2:D,Платежи!B2:B,A'+r+',Платежи!F2:F,"Зачислен")-SUMIFS(Платежи!D2:D,Платежи!B2:B,A'+r+',Платежи!F2:F,"Возврат"))');sh.getRange(r,10).setFormula('=IF(A'+r+'="","",H'+r+'-I'+r+')');}}
function newRow_(){const sh=SpreadsheetApp.getActiveSheet(),prefix={'Компании':'C','Пользователи':'U','Заказы':'O','Позиции':'I','Отгрузки':'S','Состав отгрузок':'SI','Платежи':'P','Документы':'D','Обращения':'R'}[sh.getName()];if(!prefix)throw Error('Выберите рабочий лист.');const lock=LockService.getDocumentLock();lock.waitLock(10000);try{const r=append_(sh.getName(),[prefix+'-'+uuid_().slice(0,10)]);formulas_(sh,r);sh.setActiveSelection('B'+r);}finally{lock.releaseLock();}}

const PUBLIC_FIELDS_={"Компании": ["ID компании", "Название", "ИНН", "КПП", "Юридический адрес", "Адрес доставки", "Контакт", "Телефон", "Email", "Менеджер", "Email менеджера", "Телефон менеджера", "Договор", "Дата договора", "Условия оплаты", "Лимит, ₽", "Статус", "Комментарий для клиента"], "Заказы": ["ID заказа", "ID компании", "Дата", "Название", "Статус", "Плановая дата", "Комментарий для клиента", "Сумма, ₽", "Оплачено, ₽", "Остаток, ₽"], "Позиции": ["ID позиции", "ID заказа", "Артикул", "Наименование", "Количество", "Ед.", "Цена, ₽", "Сумма, ₽", "Гарантия", "Серийный номер"], "Отгрузки": ["ID отгрузки", "ID заказа", "Статус", "Плановая дата", "Дата отправки", "Дата получения", "Способ", "Перевозчик", "Трек", "Адрес", "Получатель", "Телефон", "Комментарий для клиента"], "Состав отгрузок": ["ID строки", "ID отгрузки", "ID позиции", "Количество"], "Платежи": ["ID платежа", "ID заказа", "Дата", "Сумма, ₽", "Назначение", "Статус"], "Документы": ["ID документа", "ID компании", "ID заказа", "Тип", "Номер", "Дата", "Название", "Ссылка", "Статус"], "Обращения": ["ID обращения", "ID компании", "ID пользователя", "Дата", "Тема", "Текст", "Статус", "Ответ менеджера", "Обновлено"]};
function publicRow_(name,r){return Object.fromEntries(PUBLIC_FIELDS_[name].map(k=>[k,r[k]===undefined?"":r[k]]));}
